modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="hexbound"
version="${file.jarVersion}"
displayName="Hexbound"
displayURL="https://github.com/Cypher121/hexbound/"
authors="Cypher121"
description='''
Addon for Hexcasting adding programmable Constructs and more
'''

[[dependencies.hexbound]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.hexbound]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.hexbound]]
modId="hexcasting"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"
