[versions]
minecraft = "1.21.1"
neoforge = "21.1.28"
kotlin = "2.0.0"
hexcasting = "1.21.1-0.12.0"
paucal = "0.7.0"
geckolib = "4.6.4"
patchouli = "1.21-88-NEOFORGE"
moddev = "2.0.74"

[libraries]
minecraft = { module = "net.neoforged:neoforge", version.ref = "neoforge" }
hexcasting = { module = "at.petrak.hexcasting:hexcasting-neoforge-1.21.1", version.ref = "hexcasting" }
paucal = { module = "at.petrak.paucal:paucal-neoforge-1.21.1", version.ref = "paucal" }
geckolib = { module = "software.bernie.geckolib:geckolib-neoforge-1.21.1", version.ref = "geckolib" }
patchouli = { module = "vazkii.patchouli:Patchouli", version.ref = "patchouli" }

[plugins]
moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
